service: phapi-core-idp

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

custom:
  serverless-offline:
    httpPort: 5506
    noPrependStageInUrl: true

functions:
  api:
    handler: dist/app-lambda.handler
    events:
      - http:
          cors: true
          path: "/{proxy+}"
          method: any
